words:
  - Naruto
  - One Piece
  - Dragon Ball
  - Bleach
  - Fairy Tail
  - Berserk
  - Haikyuu
  - Elfen Lied
  - Nana
  - Mob Psycho
  - Noragami
  - Gintama
  - Parasyte
  - Clannad
  - K-On
  - ReLIFE
  - Steins Gate
  - Re Zero
  - Violet Evergarden
  - Akame ga Kill
  - Psycho Pass
  - Maid Sama
  - Kiznaiver
  - Hinamatsuri
  - Mushishi
  - Durarara
  - Kakegurui
  - KonoSuba
  - Baccano
  - Outlaw Star
  - Hellsing
  - Black Lagoon
  - Angel Beats
  - Zombieland
  - Guilty Crown
  - Anohana
  - Wotakoi
  - Kekkai Sensen
  - Tonikaku Kawaii
