discord:
  webhookUrl: 'Tu webhook de discord/Your discord webhook'  # Reemplaza con tu URL de webhook
  embed:
    title: 'Nuevo Anime: {name}'
    description: 'Descripción: {description}'
    color: 3447003  # Color en hexadecimal (ejemplo: verde)
    episodeField:
      name: 'Episodios'
      value: '{episodes}'
    releaseField:
      name: 'Fecha de lanzamiento'
      value: '{releaseDate}'
    imageUrl: '{imageUrl}'
    viewAnimeField:
      name: "Ver Anime"
      url: "http://localhost:3000/anime/${slug}" # Ruta de visualización del anime
    roleId: "Id de tu rol de discord/Id of your discord role" # Agrega aquí el ID del rol